### ISSUE TITLE
生成不需要的findviewid

### ISSUE THREAD

**Issue by Locker-Lou** [BigFootprint/AndroidViewGenerator#1]
在弹框里不勾选某些控件后，变量声明会不生成，但findviewbyid的代码仍旧会生成。
![image](https://cloud.githubusercontent.com/assets/6009179/13341495/3f56366a-dc74-11e5-9e43-cdfbae0dea05.png)

**Comment by qianyuebits** [comment]
确实有这个问题，多谢指出，近期修复。

**Comment by qianyuebits** [comment]
修复
