### ISSUE TITLE
无法使用该插件

### ISSUE THREAD

**Issue by gongzelong0718** [BigFootprint/AndroidViewGenerator#2]
在plugins的repo里没有搜索到AndroidViewGenerator，只有Android Code Generator.
下载了Jar包到本地，放到了C:\Users\HEcom.AndroidStudio2.0\config\plugins下。
然后Install from Disk...

加载不进来，提示：
Fail to load plugin descriptor from file AndroidViewGenerator.jar

**Comment by qianyuebits** [comment]
确实搜不到了，多谢提醒，已经联系JetBrains了。你是从[这里](https://plugins.jetbrains.com/plugin/8219?pr=)下载的么？我试了一下是可以安装的，请问你的Android Studio版本是多少的？

**Comment by gongzelong0718** [comment]
Anddroid Studio 2.0的。
是从这里下载的，刚按这个地址重新下载了一下，可以安装了。
原因好像是之前下载的jar包不完整。
感谢您的回复。

**Comment by qianyuebits** [comment]
好的，有问题欢迎继续反馈~
